In [1]:
#Este es un comentario porque empieza con #
print("Hola Mundo") #impresión de un string
print(4) # impresión de un número
hola = 'Hola Mundo '
print(hola)

Hola Mundo
4
Hola Mundo 


In [ ]:
x=5
print(x)

y=x+2.5
print(y)

In [2]:
x = 3 

In [3]:
print("- Tipo de x:")
print(type(x)) # Imprime el tipo (o `clase`) de x

- Tipo de x:
<class 'int'>


In [4]:
print("- Valor de x:")
print(x)       # Imprimir un valor

- Valor de x:
3


In [5]:
print("- x+1:")
print(x + 1)   # Suma: imprime "4"

- x+1:
4


In [ ]:
x += 1 
print("- x modificado:")
print(x)  # Imprime "4"

In [ ]:
print("- Varias cosas en una línea:")
print(1,2,x,5*2) # imprime varias cosas a la vez

In [ ]:
### Flotantes ###

y = 2.5 
print("- Tipo de y:")
print(type(y)) # Imprime el tipo de y
print("- Varios valores en punto flotante:")
print(y, y + 1, y * 2.5, y ** 2) # Imprime varios números en punto flotante

In [6]:
### Booleanos ###

v1 = True #el valor verdadero se escribe True 
v2 = False #el valor verdadero se escribe False

print("- Valores de v1 y v2:")
print(v1,v2)

- Valores de v1 y v2:
True False


In [7]:

print("- Tipo de v1:")
print(type(v1)) # Imprime la clase de un valor booleano ('bool')


- Tipo de v1:
<class 'bool'>


In [8]:
print("- v1 and v2:")
print(v1 and v2) # y lógico; imprime False
print(v1 or v2)  # o lógico; imprime True
print(not v1)   # negación lógica, imprime False

- v1 and v2:
False
True
False


In [ ]:
print(3 == 5)  # Imprime False ya que son distintos
print(3 != 5)  # Imprime True ya que son distintos
print(3 < 5)  # Imprime True ya que 3 es menor que 5

In [ ]:
Lista = []

In [ ]:
print("- Lista con 4 números:")
a=[57,45,7,13] # una lista con cuatro números
print(a)

In [ ]:
# la función `len` me da la longitud de la lista
print("- Longitud de la lista:")
n=len(a)
print(n)

In [ ]:
print("- Lista con 3 strings:")
b=["hola","chau","buen día"] # una lista con tres strings
print(b)

In [ ]:
#Para acceder a sus elementos, se utiliza el []
# Los índices comienzan en 0
print("- Elemento con índice 0 de la lista:")
print(b[0])
print("- Elemento con índice 1 de la lista:")
print(b[1])
print("- Elemento con índice 2 de la lista:")
print(b[2])

In [ ]:
# para crear una lista vacía, (sin elementos), simplemente ponemos []
vacia=[]
print("Lista vacía:")
print(vacia)

In [9]:
#por último, le podés agregar elementos a una lista con el método `append`
print("- Una lista con 3 strings:")
a=['una','lista','de']
print(a)

- Una lista con 3 strings:
['una', 'lista', 'de']


In [10]:

print("- La misma lista luego de agregarle un string más:")
a.append('strings')
print(a)

- La misma lista luego de agregarle un string más:
['una', 'lista', 'de', 'strings']


In [11]:
a.pop(0)

'una'

In [12]:
a

['lista', 'de', 'strings']

In [14]:
li = [1,2,3,4,5,5]

In [15]:
li.pop(0) #se elimina apartir del index

1

In [16]:
li.clear() #se limpia toda la lista

In [ ]:
li.pop(-1) #se elimina el ultimo elemento

In [ ]:
li = ['Alice', 'Bob', 'Charlie', 'Bob', 'Dave']


In [ ]:
li.remove('Alice')

In [17]:
l = [0, 10, 20, 30, 40, 50]
del l[2:5]
l

[0, 10, 50]

In [18]:
l = [0, 10, 20, 30, 40, 50]
del l[-2:]
print(l)

[0, 10, 20, 30]


In [ ]:
l = [0, 10, 20, 30, 40, 50]
del l[:]
print(l)

In [ ]:
l = ['Alice', 'Bob', 'Charlie', 'Bob', 'David']
print(l)


In [ ]:
print([s for s in l if s != 'Bob'])

In [ ]:
#Podés crear una tupla con valores entre () separados por ,
a=(1,2,57,4)
print("- Una tupla de cuatro elementos:")
print(a)
print("- El elemento con índice 2:")
print(a[2])
print("- Los elementos entre los índices 0 y 2:")
print(a[0:2])

In [ ]:
edad = 25

print("La persona es")
if edad < 18: # el if termina con : para indicar donde acaba la condición
    # el print va indentado con 4 espacios para indicar que está dentro del
    # cuerpo del if
    print("Menor") 
else:
    #Lo mismo con este print
    print("Mayor")
    
print("De edad")

In [ ]:
print("- Impresion de los elementos de la lista:")

# Imprimir los strings de mi_lista por separado
mi_lista=["img","python","numpy"]
for s in mi_lista:
    print(s)# este print va con indentación


In [ ]:
    
#calcular la suma de los números e imprimirla
suma=0
mis_numeros=[5,8,17,12]
for numero in mis_numeros:
    suma=suma+numero
print("- La suma de los números es:")
print(suma)

In [20]:
import numpy as np

In [ ]:
#Crear un vector con valores dentro del rango 10 a 49
a = np.arange(10,50)
a

In [ ]:
#Invertir el vector
a[::-1]

In [21]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [22]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
#Crear una matriz 3x3 con valores de 0 a 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.identity(6)

In [25]:
a = np.random.random((3,3))
b = np.random.random((3,3))
print(a,b)
a == b 

[[0.8517207  0.79192755 0.16996856]
 [0.84342572 0.72144639 0.85135095]
 [0.33404302 0.80580423 0.33236869]] [[0.07110096 0.72337598 0.3189811 ]
 [0.97188101 0.08966665 0.78894601]
 [0.83594013 0.82597663 0.04990972]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [47]:
#esta funcion recibe dos números y devuelve su suma

def sumar(a,b):
    return a+b


c=sumar(2,5)
print("2+5=")
print(c)


#esta funcion recibe una lista y devuelve la suma de sus elementos
def sumar_todos(lista):
    suma=0
    for v in lista:
        suma+=v
    return suma

mi_lista=[54,12,99,15]
print("los elementos de la lista suman:")
print(sumar_todos(mi_lista))

2+5=
7
los elementos de la lista suman:
180


In [ ]:
suma = sumar_todos(mi_lista)

In [ ]:
#Ejercicio
# Escribir una función que reciba una lista y un valor, 
#y devuelva la cantidad de veces que aparece ese valor en la lista

def ocurrencias(lista,valor):
    # IMPLEMENTAR
    return 0


l=[1,4,2,3,5,1,4,2,3,6,1,7,1,3,5,1,1,5,3,2]
v=2

print(ocurrencias(l,v))

In [27]:
def ocurrencias(lista,valor):
    count = 0
    for ele in lista: 
        if (ele == valor): 
            count = count + 1

    a = np.random.random((n,n))
    indentidad = np.identity(n)
    diagonal_iden = np.diag(indentidad)
    diagonal_iden_a = np.diag(a)
    boole = diagonal_iden.all() == diagonal_iden_a.all()
    return count , a , boole

In [45]:
lst = [8, 6, 8, 10, 8, 20, 10, 8, 8] 
x = 8
count , a , boole = ocurrencias(lst,x)

In [46]:
count , a , boole

(5,
 array([[0.87318033, 0.03839277, 0.6402581 , 0.54324396, 0.97985708],
        [0.76504734, 0.66342341, 0.62933831, 0.83255443, 0.97123556],
        [0.67582518, 0.33345242, 0.09571765, 0.96127013, 0.81472005],
        [0.26859107, 0.93749547, 0.25244821, 0.96586181, 0.56579606],
        [0.65409396, 0.00621326, 0.28394863, 0.59076099, 0.46185151]]),
 True)

In [43]:
def ocurrencias(lst, x): 
    n = lst.count(x)
    a = np.random.random((n,n))
    indentidad = np.identity(n)
    diagonal_iden = np.diag(indentidad)
    diagonal_iden_a = np.diag(a)
    boole = diagonal_iden.all() == diagonal_iden_a.all()

    return n,a,boole
  
lst = [8, 6, 8, 10, 8, 20, 10, 8, 8] 
x = 8
n,a,boole = ocurrencias(lst,x)

In [44]:
n,a,boole

(5,
 array([[0.48265666, 0.38965504, 0.78939823, 0.67977802, 0.50320364],
        [0.75296771, 0.23986568, 0.66674154, 0.56210365, 0.84783956],
        [0.13638022, 0.27323926, 0.5989428 , 0.65090353, 0.76727862],
        [0.96596181, 0.3434753 , 0.83240823, 0.69529098, 0.02113831],
        [0.55794963, 0.29011529, 0.5065356 , 0.33928643, 0.10910274]]),
 True)

In [38]:
randnums= np.random.random(1,3, size=(x,x))

TypeError: random() takes at most 1 positional argument (2 given)

(8, 8)

In [30]:
lst = [8, 6, 8, 10, 8, 20, 10, 8, 8] 

In [33]:
a = np.array(lst)

In [35]:
a+2

array([10,  8, 10, 12, 10, 22, 12, 10, 10])